---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-urbackup-backups-pv
spec:
  capacity:
    storage: 7Ti
  accessModes:
    - ReadWriteMany
  local:
    path: /mnt/local2/backups.sparks.codes/backups
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - tango

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-urbackup-backups-pvc
  namespace: media
spec:
  volumeName: local-urbackup-backups-pv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 7Ti
