---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calibre
  # - docuseal
  - immich
  - jellyfin
  - metube
  - nextcloud
  - paperless-ngx
  - qbittorrent
  # - sftp-access
